# roles/event_agent/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_event_agent_namespace }}"
    - path: "{{ openio_event_agent_sysconfig_dir }}/{{ openio_event_agent_servicename }}"
    - path: "/var/log/oio/sds/{{ openio_event_agent_namespace }}/{{ openio_event_agent_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "event_agent.conf.j2"
      dest: "{{ openio_event_agent_sysconfig_dir }}/\
        {{ openio_event_agent_servicename }}/{{ openio_event_agent_servicename }}.conf"
    - src: "event_agent_handlers.conf.j2"
      dest: "{{ openio_event_agent_sysconfig_dir }}/\
        {{ openio_event_agent_servicename }}/oio-event-handlers.conf"
    - src: "gridinit_event_agent.conf.j2"
      dest: "{{ openio_event_agent_gridinit_dir }}/{{ openio_event_agent_gridinit_file_prefix }}\
        {{ openio_event_agent_servicename }}.conf"
  register: _event_agent_conf

- name: "Generate configuration files (event delete)"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "event_delete.conf.j2"
      dest: "{{ openio_event_agent_sysconfig_dir }}/\
        {{ openio_event_agent_servicename }}/{{ openio_event_delete_servicename }}.conf"
    - src: "event_delete_handlers.conf.j2"
      dest: "{{ openio_event_agent_sysconfig_dir }}/\
        {{ openio_event_agent_servicename }}/oio-event-handlers-delete.conf"
    - src: "gridinit_event_delete.conf.j2"
      dest: "{{ openio_event_agent_gridinit_dir }}/{{ openio_event_agent_gridinit_file_prefix }}\
        {{ openio_event_delete_servicename }}.conf"
  register: _event_delete_conf
  when: openio_event_agent_tube_delete_enabled

- name: "Ensure proper state for gridinit service"
  file:
    name: "{{ openio_event_agent_gridinit_dir }}/{{ openio_event_agent_gridinit_file_prefix }}\
      {{ openio_event_delete_servicename }}.conf"
    state: "{{ 'file' if openio_event_agent_tube_delete_enabled else 'absent' }}"
  register: _event_delete_conf
  ignore_errors: "{{ ansible_check_mode }}"

- name: reload gridinit config
  command: gridinit_cmd reload
  when:
    - _event_agent_conf.changed or _event_delete_conf.changed
    - not openio_event_agent_provision_only

- name: restart event_agent
  command: gridinit_cmd restart {{ openio_event_agent_namespace }}-{{ openio_event_agent_servicename }}
  when:
    - _event_agent_conf.changed
    - not openio_event_agent_provision_only
  tags: configure

- name: restart event_delete
  command: gridinit_cmd restart {{ openio_event_agent_namespace }}-{{ openio_event_delete_servicename }}
  when:
    - _event_delete_conf.changed
    - not openio_event_agent_provision_only
  tags: configure
...
